Implementation for table renames at the table service and client level (#329)
## Summary

<!--- HINT: Replace #nnn with corresponding Issue number, if you are
fixing an existing issue -->

[Issue](https://github.com/linkedin/openhouse/issues/#nnn) Briefly
discuss the summary of the changes made in this
pull request in 2-3 lines.

## Changes

- [x] Client-facing API Changes
- [x] Internal API Changes
- [ ] Bug Fixes
- [x] New Features
- [ ] Performance Improvements
- [ ] Code Style
- [ ] Refactoring
- [ ] Documentation
- [x] Tests

Adds Table Rename functionality in OpenHouse
Building off a previous PR
https://github.com/linkedin/openhouse/pull/323

**High level design:** Rename only on the catalog side, keep the
underlying location consistent. This is to maintain authorization
without needing to synchronize permissions between different locations.
Current design only supports rename on the table layer, not on the
database layer but can be extended for database level support.

Since Table ID and table uri is generated using the iceberg table
metadata, need to update the metadata then perform a HTS call. Since HTS
takes in a metadata location, it ensures that the HTS rename is atomic
with the metadata update.

Spark syntax is the follows:
```
      spark.sql("ALTER TABLE openhouse.db.rename_test RENAME TO db.rename_test_renamed");
```

Added audit events, metric name 
Table Service URI is located as a PATCH endpoint on
`/v1/databases/{fromDatabaseId}/tables/{fromTableId}/rename`


For all the boxes checked, please include additional details of the
changes made in this pull request.

## Testing Done
<!--- Check any relevant boxes with "x" -->

- [ ] Manually Tested on local docker setup. Please include commands
ran, and their output.
- [ ] Added new tests for the changes made.
- [ ] Updated existing tests to reflect the changes made.
- [ ] No tests added or updated. Please explain why. If unsure, please
feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in
production. Please explain.

For all the boxes checked, include a detailed description of the testing
done for the changes made in this pull request.

Unit tests
Tested on local docker
```
scala> spark.sql("CREATE TABLE openhouse.db.tb (ts timestamp, col1 string, col2 string) PARTITIONED BY (days(ts))").show()
++
||
++
++

scala> spark.sql("INSERT INTO TABLE openhouse.db.tb VALUES (current_timestamp(), 'val1', 'val2')")
res5: org.apache.spark.sql.DataFrame = []

scala> spark.sql("ALTER TABLE openhouse.db.tb RENAME TO db.tb2").show()
++
||
++
++


scala> spark.sql("SELECT * FROM openhouse.db.tb2").show()
+--------------------+----+----+
|                  ts|col1|col2|
+--------------------+----+----+
|2025-06-05 20:47:...|val1|val2|
+--------------------+----+----+

scala> spark.sql("SHOW TBLPROPERTIES openhouse.db.tb2").show(false)
+------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
|key                                       |value                                                                                                              |
+------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
|openhouse.tableUUID                       |5a197486-09ba-41ab-98ac-31eaee3b85cb                                                                               |
|openhouse.tableLocation                   |/data/openhouse/db/tb-5a197486-09ba-41ab-98ac-31eaee3b85cb/00002-0794acfe-43d6-47aa-9675-84f26a405591.metadata.json|
|write.metadata.delete-after-commit.enabled|true                                                                                                               |
|write.metadata.previous-versions-max      |28                                                                                                                 |
|openhouse.tableCreator                    |openhouse                                                                                                          |
|openhouse.tableId                         |tb2                                                                                                                |
|openhouse.tableType                       |PRIMARY_TABLE                                                                                                      |
|policies                                  |                                                                                                                   |
|openhouse.creationTime                    |1749159727452                                                                                                      |
|openhouse.databaseId                      |db                                                                                                                 |
|openhouse.clusterId                       |LocalHadoopCluster                                                                                                 |
|format                                    |iceberg/orc                                                                                                        |
|openhouse.tableVersion                    |/data/openhouse/db/tb-5a197486-09ba-41ab-98ac-31eaee3b85cb/00001-773f3b3d-3077-4fa3-bdff-d2467402dcaa.metadata.json|
|openhouse.tableUri                        |LocalHadoopCluster.db.tb2                                                                                          |
|openhouse.lastModifiedTime                |1749159751975                                                                                                      |
|openhouse.appended_snapshots              |5805411895027074554                                                                                                |
|write.format.default                      |orc                                                                                                                |
|write.parquet.compression-codec           |zstd                                                                                                               |
|current-snapshot-id                       |5805411895027074554                                                                                                |
+------------------------------------------+-------------------------------------------------------------------------------------------------------------------+

```

Testing edge cases:
1. Fail renames across DBs
```
scala> spark.sql("ALTER TABLE openhouse.db.tb RENAME TO db2.tb2").show
com.linkedin.openhouse.javaclient.exception.WebClientResponseWithMessageException: 400 Bad Request , {"status":"BAD_REQUEST","error":"Bad Request","message":"Rename table across databases is not supported. Cannot rename table tb from db to db2","stacktrace":null,"cause":"Not Available"}
```

2. Fails renames if destination already exists
```
scala> spark.sql("ALTER TABLE openhouse.db.tb2 RENAME TO db.tb3").show()
com.linkedin.openhouse.javaclient.exception.WebClientResponseWithMessageException: 409 Conflict , {"status":"CONFLICT","error":"Conflict","message":"Table LocalHadoopCluster.db.tb3 already exists","stacktrace":null,"cause":"Not Available"}
  at com.linkedin.openhouse.javaclient.OpenHouseCatalog.lambda$renameTable$6(OpenHouseCatalog.java:251)
```
3. Fail renames if table doesn't exist
```
scala> spark.sql("ALTER TABLE openhouse.db.tb RENAME TO db.tb3").show()
org.apache.spark.sql.catalyst.analysis.NoSuchTableException: Table db.tb not found
  at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:146)
```

4. Block renames if HTS is down, validated that after bringing service
back up table ID from metadata remains consistent.
```
scala> spark.sql("ALTER TABLE openhouse.db.tb2 RENAME TO db.tb3").show()
com.linkedin.openhouse.javaclient.exception.WebClientResponseWithMessageException: 500 Internal Server Error , {"status":"INTERNAL_SERVER_ERROR","error":"Internal Server Error","message":"java.lang.RuntimeException: UNKNOWN and unhandled failure from HTS:","stacktrace":null,"cause":"No route to host: openhouse-housetables/172.18.0.10:8080; nested exception is io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: openhouse-housetables/172.18.0.10:8080"}
  at com.linkedin.openhouse.javaclient.OpenHouseTableOperations.lambda$doRefresh$2(OpenHouseTableOperations.java:92)
```

5. Allows creates using the old table name after a rename
```
scala> spark.sql("ALTER TABLE openhouse.db.tb RENAME TO db.tb2").show
++
||
++
++

scala> spark.sql("CREATE TABLE openhouse.db.tb (ts timestamp, col1 string, col2 string) PARTITIONED BY (days(ts))").show()
++
||
++
++

scala> spark.sql("SHOW TABLES in openhouse.db").show
+---------+---------+
|namespace|tableName|
+---------+---------+
|       db|       tb|
|       db|      tb2|
+---------+---------+

```

6. Ensures that permissions are maintained when renaming a table
```
scala> spark.sql("GRANT SELECT ON TABLE openhouse.db.tb TO u_tableowner").show
++
||
++
++

scala> spark.sql("SHOW GRANTS ON TABLE openhouse.db.tb").show
+---------+------------+
|privilege|   principal|
+---------+------------+
|   SELECT|u_tableowner|
+---------+------------+

scala> spark.sql("ALTER TABLE openhouse.db.tb RENAME TO db.tb2").show
++
||
++
++

scala> spark.sql("SHOW GRANTS ON TABLE openhouse.db.tb2").show
+---------+------------+
|privilege|   principal|
+---------+------------+
|   SELECT|u_tableowner|
+---------+------------+

scala> spark.sql("SHOW GRANTS ON TABLE openhouse.db.tb").show
com.linkedin.openhouse.javaclient.exception.WebClientResponseWithMessageException: 404 Not Found , {"status":"NOT_FOUND","error":"Not Found","message":"User table db.tb cannot be found","stacktrace":null,"cause":"Not Available"}
```

7. Fail renames if the table and database names do not change
```
scala> spark.sql("ALTER TABLE openhouse.db.tb2 RENAME TO db.tb2").show()
com.linkedin.openhouse.javaclient.exception.WebClientResponseWithMessageException: 400 Bad Request , {"status":"BAD_REQUEST","error":"Bad Request","message":"Cannot rename a table to the same current db name and table name: tb2","stacktrace":null,"cause":"Not Available"}
```

# Additional Information

- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the
description.

For all the boxes checked, include additional details of the changes
made in this pull request.