Allow PUBLIC user which can have global table permissions (#289)
## Summary

<!--- HINT: Replace #nnn with corresponding Issue number, if you are
fixing an existing issue -->

[Issue](https://github.com/linkedin/openhouse/issues/#nnn) Briefly
discuss the summary of the changes made in this
pull request in 2-3 lines.

Support syntax for a group encapsulating all users, denoted as
`"PUBLIC"`. `"PUBLIC"` access to tables can be granted privileges to all
users. With the local OPAHandler only support TABLE_VIEWER role with
PUBLIC.

The Authorization handler backend handles PUBLIC user with the wildcard
regex `*`.
But when fetching grants for a table it should show up as PUBLIC.

Similar to the functionality of PUBLIC in Oracle
https://docs.oracle.com/cd/A97630_01/server.920/a96521/privs.htm#15505

Other design consideration was to change the Principal field in requests
from String to an object instead of creating a mapper like
https://github.com/linkedin/openhouse/blob/3807ad24f25112b57c716579cff76cfe831ffe37/integrations/spark/spark-3.1/openhouse-spark-runtime/src/main/scala/com/linkedin/openhouse/spark/sql/catalyst/constants/Principal.scala,
but it would require a change to both server and client which is not
backwards compatible.

## Changes

- [x] Client-facing API Changes
- [ ] Internal API Changes
- [ ] Bug Fixes
- [ ] New Features
- [ ] Performance Improvements
- [ ] Code Style
- [ ] Refactoring
- [ ] Documentation
- [ ] Tests

For all the boxes checked, please include additional details of the
changes made in this pull request.

## Testing Done
<!--- Check any relevant boxes with "x" -->

- [x] Manually Tested on local docker setup. Please include commands
ran, and their output.
- [x] Added new tests for the changes made.
- [x] Updated existing tests to reflect the changes made.
- [ ] No tests added or updated. Please explain why. If unsure, please
feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in
production. Please explain.

For all the boxes checked, include a detailed description of the testing
done for the changes made in this pull request.

Tested on local docker to ensure syntax is handled correctly with local
OPA handler.

```

spark.sql("ALTER TABLE openhouse.db.tb SET POLICY (SHARING=true)").show

spark.sql("GRANT SELECT ON TABLE openhouse.db.tb TO u_tableowner").show

spark.sql("SHOW GRANTS ON TABLE openhouse.db.tb").show

scala> spark.sql("SHOW GRANTS ON TABLE openhouse.db.tb").show
+---------+---------+
|privilege|principal|
+---------+---------+
|   SELECT|   PUBLIC|
+---------+---------+

Using another spark user

scala> spark.sql("SELECT * from openhouse.db.tb").show()
+--------------------+----+----+                                                
|                  ts|col1|col2|
+--------------------+----+----+
|2025-02-19 17:58:...|val1|val2|
+--------------------+----+----+


scala> spark.sql("REVOKE SELECT ON TABLE openhouse.db.tb FROM PUBLIC").show
++
||
++
++


scala> spark.sql("SHOW GRANTS ON TABLE openhouse.db.tb").show
+---------+---------+
|privilege|principal|
+---------+---------+
+---------+---------+

From another spark user
scala> spark.sql("SELECT * from openhouse.db.tb").show()
com.linkedin.openhouse.javaclient.exception.WebClientResponseWithMessageException: 403 Forbidden , {"status":"FORBIDDEN","error":"Forbidden","message":"Operation on table db.tb failed as user u_tableowner is unauthorized","stacktrace":null,"cause":"Not Available"}
  at com.linkedin.openhouse.javaclient.OpenHouseTableOperations.lambda$doRefresh$2(OpenHouseTableOperations.java:90)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.Mono.lambda$onErrorResume$32(Mono.java:3887)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.Operators.error(Operators.java:198)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.Mono.subscribe(Mono.java:4490)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106)
  at com.linkedin.openhouse.relocated.reactor.core.publisher.Operators.error(Operators.java:198)

```


# Additional Information

- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the
description.

For all the boxes checked, include additional details of the changes
made in this pull request.