Fix relocation of commons-logging dependency in apps.spark-common module (#382)
## Summary


[Issue]

Launching the Job scheduler process fails with the following exception 

```2025-10-15 23:00:30 INFO  LiJobsScheduler:60 - Starting LI jobs scheduler
Exception in thread "main" java.lang.NoClassDefFoundError: openhouse/relocated/org.apache.commons.logging.LogFactory
        at org.apache.commons.logging.LogFactory.class$(LogFactory.java:1021)
        at org.apache.commons.logging.LogFactory.<clinit>(LogFactory.java:1674)
        at org.springframework.retry.backoff.ExponentialBackOffPolicy.<init>(ExponentialBackOffPolicy.java:45)
        at org.springframework.retry.backoff.BackOffPolicyBuilder.build(BackOffPolicyBuilder.java:165)
        at com.linkedin.openhouse.jobs.util.RetryUtil.<clinit>(RetryUtil.java:20)
        at com.linkedin.openhouse.jobs.client.TablesClientFactory.create(TablesClientFactory.java:28)
        at com.linkedin.openhouse.jobs.scheduler.LiJobsScheduler.main(LiJobsScheduler.java:65)
```

Root-cause 

1. The failure was caused by not being able to load class from
class-path:

```
Exception in thread "main" java.lang.NoClassDefFoundError: openhouse/relocated/org.apache.commons.logging.LogFactory  .

```

2. From jar-file inspection, the class was not relocated and retained as
is: `org.apache.commons.logging.LogFactory` in both openhouse-oss and
li-openhouse projects. Here are the class file contents extracted from
li-openhouse project:
https://gist.github.com/shanthoosh/1679e13cfd3ab81e4c43498639e09939 .

3. Even though the class was not relocated but the individual literals
corresponding to FQCN that are defined in the class were relocated(?)
```
  public static final String FACTORY_PROPERTY = "openhouse/relocated/org.apache.commons.logging.LogFactory";
  public static final String HASHTABLE_IMPLEMENTATION_PROPERTY = "openhouse/relocated/org.apache.commons.logging.LogFactory.HashtableImpl";
  ```
4.This partial relocation was root cause of above failure. We should either relocate both string literal and FQCN or not relocate-at-all. Relevant shadow-jar issue:  https://github.com/GradleUp/shadow/issues/305#issuecomment-2978978772



## Changes

Switch from dot notation to regex based replacement to exclude the relocated packages.

- [ ] Client-facing API Changes
- [ ] Internal API Changes
- [ ] Bug Fixes
- [ ] New Features
- [ ] Performance Improvements
- [ ] Code Style
- [ ] Refactoring
- [ ] Documentation
- [ ] Tests

For all the boxes checked, please include additional details of the changes made in this pull request.  

## Testing Done

From local build, the commons.lang classes and string literals in them were not relocated. 

- [x] Manually Tested on local docker setup. Please include commands ran, and their output.
- [ ] Added new tests for the changes made.
- [ ] Updated existing tests to reflect the changes made.
- [ ] No tests added or updated. Please explain why. If unsure, please feel free to ask for help.
- [ ] Some other form of testing like staging or soak time in production. Please explain.

For all the boxes checked, include a detailed description of the testing done for the changes made in this pull request.

# Additional Information

- [ ] Breaking Changes
- [ ] Deprecations
- [ ] Large PR broken into smaller PRs, and PR plan linked in the description.

For all the boxes checked, include additional details of the changes made in this pull request.